# Generated by Django 6.1.1 on 2026-09-09 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamados', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chamado',
            name='data_finalizacao',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de finalização'),
        ),
        migrations.AlterField(
            model_name='chamado',
            name='numero',
            field=models.PositiveIntegerField(editable=False, unique=True, verbose_name='Número'),
        ),
    ]
