# Generated by Django 6.1.1 on 2026-09-09 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamados', '0002_chamado_data_finalizacao_alter_chamado_numero'),
    ]

    operations = [
        migrations.AddField(
            model_name='chamado',
            name='resolucao',
            field=models.TextField(blank=True, verbose_name='Resolução'),
        ),
    ]
