# Generated by Django 6.1.1 on 2026-09-09 02:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamados', '0003_chamado_resolucao'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricoChamado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ABERTO', 'Aberto'), ('ATENDIMENTO', 'Em atendimento'), ('FINALIZADO', 'Finalizado')], max_length=20, verbose_name='Status')),
                ('data', models.DateTimeField(auto_now_add=True, verbose_name='Data')),
                ('chamado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico', to='chamados.chamado', verbose_name='Chamado')),
            ],
        ),
    ]
