# Generated by Django 6.1.1 on 2026-09-10 02:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamados', '0005_local'),
    ]

    operations = [
        migrations.AddField(
            model_name='chamado',
            name='local_cadastrado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='chamados', to='chamados.local', verbose_name='Local'),
        ),
    ]
