# Generated by Django 6.1.1 on 2026-09-10 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chamados', '0006_chamado_local_cadastrado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chamado',
            name='local',
        ),
    ]
