# Generated by Django 6.1.1 on 2026-09-13 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamados', '0007_remove_chamado_local'),
    ]

    operations = [
        migrations.AddField(
            model_name='chamado',
            name='solicitante',
            field=models.CharField(blank=True, max_length=150, verbose_name='Solicitante'),
        ),
    ]
