# Generated by Django 6.1.1 on 2026-09-17 02:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamados', '0009_chamado_operador_finalizacao'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroAtendimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField(verbose_name='Ocorrência')),
                ('data', models.DateTimeField(auto_now_add=True, verbose_name='Data')),
                ('chamado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_atendimento', to='chamados.chamado', verbose_name='Chamado')),
                ('operador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registros_atendimento', to=settings.AUTH_USER_MODEL, verbose_name='Operador')),
            ],
            options={
                'verbose_name': 'Registro de atendimento',
                'verbose_name_plural': 'Registros de atendimento',
                'ordering': ['data'],
            },
        ),
    ]
